#!/bin/bash


echo "Enter the number to compare between them"

read -p "Enter the fist Number : " num1

read -p "Enter the second Number : " num2

if [[ $num1 -gt $num2 ]];
then
        echo "$num1 is greater than $num2"

else
        echo "$num1 is smaller than $num2"

fi
