#!/bin/bash

<<note
This is the script of installing packages according to user required
note

echo "*************************** INSTALLING $1 *****************************"
echo ""
df -h
free -h

sudo apt-get update
sudo apt-get upgrade

sudo apt-get install $1 -y

sudo systemctl start $1
sudo systemctl enable $1
sudo systemctl status $1

echo ""
date
uptime
echo "**************************** INSTALLED $1 ******************************"
